FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --dangerously-allow-all-builds

COPY . .

RUN CI=true pnpm exec prisma generate

RUN pnpm run build

EXPOSE 3000

CMD ["node", "dist/src/main.js"]